### About Dataset

    The dataset contains information about a group of test subjects and their sleep patterns.
        Each test subject is identified by a unique "Subject ID" and their age and gender are also recorded.
        The "Bedtime" and "Wakeup time" features indicate when each subject goes to bed and wakes up each day, and
        the "Sleep duration" feature records the total amount of time each subject slept in hours.
        The "Sleep efficiency" feature is a measure of the proportion of time spent in bed that is actually spent asleep.
        The "REM sleep percentage", "Deep sleep percentage", and "Light sleep percentage" features indicate the amount of time each subject spent in each stage of sleep.
        The "Awakenings" feature records the number of times each subject wakes up during the night.

Additionally, the dataset includes information about each subject's caffeine and alcohol consumption in the 24 hours prior to bedtime, their smoking status, and their exercise frequency


Use the dataset provided to do data cleaning :
- Missing Values
- Correct Datatypes if needed
- Check and remove duplicates
- Do you notice any naming issues in the data

In [2]:
import pandas as pd

In [16]:
file_path = '/workspaces/Pythonpractrices_Waltermokwena/data_cleaning_exercize/performance.csv'
performance = pd.read_csv(file_path)
sleep_efficiency = pd.read_csv('/workspaces/Pythonpractrices_Waltermokwena/data_cleaning_exercize/Sleep_Efficiency.csv', index_col=0)
sleep_efficiency.head()

,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
ID,,,,,,,,,,,,,,
1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0

In [18]:
sleep_efficiency.isnull()

,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
ID,,,,,,,,,,,,,,
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448,False,False,False,False,False,False,False,False,False,False,False,False,False,False
449,False,False,False,False,False,False,False,False,False,False,False,False,False,False
450,False,False,False,False,False,False,False,False,False,False,True,False,False,False
451,False,False,False,False,False,False,False,False,False,False,False,False,False,False
452,False,False,False,False,False,False,False,False,False,False,False,False,False,False